[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
       "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
       "@astral/=lib/logbook/contracts/",
       "@eas/=lib/eas-contracts/contracts/",
       "forge-std/=lib/forge-std/src/"
   ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
